### ISSUE TITLE
Uninstalling datapacks

### ISSUE THREAD

**Issue by joshsharrad** [JoeJoeTV/datapacks#4]
Good Afternoon,

I cant seem to find a way to uninstall your datapacks... This is an issue and means that they will forever be in my world. I understand that deleting the datapack from the datapacks folder in the world save, but that still leaves bits behind like the /trigger command list etc.

Thanks for your help with this, hope to hear back soon,
Josh

**Comment by JoeJoeTV** [comment]
Thank you for reporting the issue, I will look into it and make a fix.

**Comment by JoeJoeTV** [comment]
Uninstall functionality has been added in 1682fffae01a3131d445f95ec17a0ae306473f8f, see README.md

**Comment by JoeJoeTV** [comment]
Uninstall functionality has been added in 1682fffae01a3131d445f95ec17a0ae306473f8f, see README.md
The datapacks will be disabled automatically and you can remove them from the datapacks folder. 

Also, can you maybe give a little feedback on the datapacks, because not many people other than me and my friends have used them and these are my first public datapacks.

Thank you in advance
